'use client';

import { useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'fr';

const translations = {
  en: {
    appName: 'Islamic Companion',
    subtitle: 'Your Daily Islamic Guide',
    quran: 'Quran',
    hadith: 'Hadith',
    prayer: 'Prayer Times',
    qibla: 'Qibla Direction',
    adhkar: 'Adhkar',
    footer: 'for the Muslim community',
    searchSurah: 'Search Surah...',
    surah: 'Surah',
    verse: 'Verse',
    verses: 'verses',
    bookmarked: 'Bookmarked',
    loading: 'Loading...',
    error: 'Error loading data',
    searchHadith: 'Search Hadith...',
    narrator: 'Narrator',
    chapter: 'Chapter',
    morning: 'Morning Adhkar',
    evening: 'Evening Adhkar',
    sleep: 'Before Sleep',
    wakeup: 'Upon Waking',
    meal: 'Before Meals',
    travel: 'Travel',
    findQibla: 'Find Qibla Direction',
    locationAccess: 'Location access required',
    grantLocation: 'Grant Location Access',
    calculating: 'Calculating...',
    qiblaDirection: 'Qibla Direction',
    yourLocation: 'Your Location',
    distance: 'Distance to Makkah',
    prayerTimesToday: 'Prayer Times Today',
    fajr: 'Fajr',
    sunrise: 'Sunrise',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    nextPrayer: 'Next Prayer',
    timeRemaining: 'Time Remaining',
    selectLocation: 'Select your location',
    search: 'Search',
    translation: 'Translation',
    bookmark: 'Bookmark',
    removeBookmark: 'Remove Bookmark',
    goToVerse: 'Go to Verse',
    arabic: 'Arabic',
    transliteration: 'Transliteration',
    repeat: 'Repeat',
    times: 'times',
  },
  ar: {
    appName: 'الرفيق الإسلامي',
    subtitle: 'دليلك الإسلامي اليومي',
    quran: 'القرآن',
    hadith: 'الحديث',
    prayer: 'أوقات الصلاة',
    qibla: 'اتجاه القبلة',
    adhkar: 'الأذكار',
    footer: 'للمجتمع الإسلامي',
    searchSurah: 'ابحث عن سورة...',
    surah: 'سورة',
    verse: 'آية',
    verses: 'آيات',
    bookmarked: 'محفوظة',
    loading: 'جاري التحميل...',
    error: 'خطأ في تحميل البيانات',
    searchHadith: 'ابحث في الأحاديث...',
    narrator: 'الراوي',
    chapter: 'الباب',
    morning: 'أذكار الصباح',
    evening: 'أذكار المساء',
    sleep: 'قبل النوم',
    wakeup: 'عند الاستيقاظ',
    meal: 'قبل الطعام',
    travel: 'السفر',
    findQibla: 'اعثر على اتجاه القبلة',
    locationAccess: 'يتطلب الوصول إلى الموقع',
    grantLocation: 'السماح بالوصول إلى الموقع',
    calculating: 'جاري الحساب...',
    qiblaDirection: 'اتجاه القبلة',
    yourLocation: 'موقعك',
    distance: 'المسافة إلى مكة',
    prayerTimesToday: 'أوقات الصلاة اليوم',
    fajr: 'الفجر',
    sunrise: 'الشروق',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    nextPrayer: 'الصلاة القادمة',
    timeRemaining: 'الوقت المتبقي',
    selectLocation: 'اختر موقعك',
    search: 'بحث',
    translation: 'الترجمة',
    bookmark: 'حفظ',
    removeBookmark: 'إزالة الحفظ',
    goToVerse: 'اذهب إلى الآية',
    arabic: 'العربية',
    transliteration: 'النسخ الصوتي',
    repeat: 'كرر',
    times: 'مرات',
  },
  fr: {
    appName: 'Compagnon Islamique',
    subtitle: 'Votre Guide Islamique Quotidien',
    quran: 'Coran',
    hadith: 'Hadith',
    prayer: 'Horaires de Prière',
    qibla: 'Direction Qibla',
    adhkar: 'Adhkar',
    footer: 'pour la communauté musulmane',
    searchSurah: 'Rechercher une Sourate...',
    surah: 'Sourate',
    verse: 'Verset',
    verses: 'versets',
    bookmarked: 'Favoris',
    loading: 'Chargement...',
    error: 'Erreur de chargement',
    searchHadith: 'Rechercher un Hadith...',
    narrator: 'Narrateur',
    chapter: 'Chapitre',
    morning: 'Adhkar du Matin',
    evening: 'Adhkar du Soir',
    sleep: 'Avant de Dormir',
    wakeup: 'Au Réveil',
    meal: 'Avant les Repas',
    travel: 'Voyage',
    findQibla: 'Trouver la Direction Qibla',
    locationAccess: 'Accès à la localisation requis',
    grantLocation: 'Autoriser la Localisation',
    calculating: 'Calcul en cours...',
    qiblaDirection: 'Direction Qibla',
    yourLocation: 'Votre Position',
    distance: 'Distance à La Mecque',
    prayerTimesToday: "Horaires de Prière Aujourd'hui",
    fajr: 'Fajr',
    sunrise: 'Lever du Soleil',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    nextPrayer: 'Prochaine Prière',
    timeRemaining: 'Temps Restant',
    selectLocation: 'Sélectionnez votre position',
    search: 'Rechercher',
    translation: 'Traduction',
    bookmark: 'Marquer',
    removeBookmark: 'Supprimer',
    goToVerse: 'Aller au Verset',
    arabic: 'Arabe',
    transliteration: 'Translittération',
    repeat: 'Répéter',
    times: 'fois',
  },
};

export function useLanguage() {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language | null;
    if (saved && ['en', 'ar', 'fr'].includes(saved)) {
      setLanguage(saved);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key];
  };

  return { language, setLanguage: changeLanguage, t };
}
